### ISSUE TITLE
Update python 3.9 to 3.11

### ISSUE THREAD

**Issue by PepperandSummer** [CSCI-GA-2820-SU23-001/orders#1]
**As a** developer
**I need** to upgrade the development environment to Python 3.11 and update requirements.txt, Makefile, and setup.cfg
**So that** we use the updated version of Python for the project

### Details and Assumptions
- Update requirements.txt, Makefile, and setup.cfg to replace nose (which is not compatible with Python 3.11) with green instead.
### Acceptance Criteria
- requirements.txt, Makefile, and setup.cfg match with the versions from https://github.com/nyu-devops/project-template
- Details changes in pr: https://github.com/nyu-devops/project-template/pull/11

**Comment by nicksome168** [comment]
Upgraded. Pls pull the latest version https://github.com/CSCI-GA-2820-SU23-001/orders/commit/d31575c2b550deb7d4272c4d714c122a2d9f2a67
