### ISSUE TITLE
Cancel Order in User Interface

### ISSUE THREAD

**Issue by un-poco** [CSCI-GA-2820-SU23-001/orders#104]
As an admin,
I need a UI that allows me to manipulate orders operations,
So that I can cancel an order.

## Details and Assumptions
The form will only intake order_id.

## Acceptance Criteria
Given I input the order_id,
When I click on the cancel button on the UI,
Then the order's status is changed to cancel in the database,
And show a success or fail message on the UI.

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/104?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
