### ISSUE TITLE
Delete Order in User Interface

### ISSUE THREAD

**Issue by un-poco** [CSCI-GA-2820-SU23-001/orders#106]
As an admin,
I need a UI that allows me to manipulate orders operations,
So that I can delete an order.

## Details 
* The form will intake order_id.

## Acceptance Criteria
Given I input order_id,
When I click on the delete button on the UI,
Then an order is deleted from the database,
And show a success or fail message on the UI.

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/106?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
