### ISSUE TITLE
Query Order in User Interface

### ISSUE THREAD

**Issue by un-poco** [CSCI-GA-2820-SU23-001/orders#107]
I need a UI that allows me to query an order with constraints
So that I can query order and know the query results

## Details 
The form will intake query conditions.

## Acceptance Criteria
Given order information in the UI,
I can input constraints in the form,
When I click on the query button on the UI,
Then an order is queried in the database,
Show a success or fail message on the UI,
And also show query results on the UI.

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/107?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
