### ISSUE TITLE
Add sad path for QUERY scenario

### ISSUE THREAD

**Issue by nicksome168** [CSCI-GA-2820-SU23-001/orders#134]
**As a** developer 
**I need** test if UI query functionality works fine even when users use it incorrectly
**So that** the service wont crash
   
 ### Details and Assumptions
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given some orders 
 When user search an order by fields that are not `status` nor `customer_id`
 Then i should see `Only support Customer_id and Status query`
```

**Comment by yjhsieh2022** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/134?planning-poker) with Zenhub @even1111112 @nicksome168 @PepperandSummer @un-poco @yjhsieh2022
