### ISSUE TITLE
Add database health check in /health endpoint

### ISSUE THREAD

**Issue by nicksome168** [CSCI-GA-2820-SU23-001/orders#135]
**As a** developer
**I need** a health endpoint
**So that** I can check if both service and the database are health in the cluster 
   
 ### Details and Assumptions
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a rest API endpoint `/health`
 When user GET `/health` endpoint on cluster
 Then I should expect 200 OK if both services are up. Otherwise 503 Service Unavailable
```

**Comment by yjhsieh2022** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/135?planning-poker) with Zenhub @even1111112 @nicksome168 @PepperandSummer @un-poco @yjhsieh2022
