### ISSUE TITLE
Need REST API to Create an Order

### ISSUE THREAD

**Issue by yjhsieh2022** [CSCI-GA-2820-SU23-001/orders#2]
**As a** user
 **I need** a way to place my orders
 **So that** I can purchase products
   
 ### Details and Assumptions
•	The base URL would be /orders
•	URL should return the new order’s URI once success
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the server is available
 When I call the URL `POST /orders`
 Then should return 201 Created if the resource is successfully created and return the newly created resource as JSON
 ```

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/2?planning-poker) with Zenhub @yjhsieh2022 @un-poco @PepperandSummer @even1111112

**Comment by PepperandSummer** [comment]
[](url)

**Comment by PepperandSummer** [comment]
mistake- reopen the issue

**Comment by PepperandSummer** [comment]
[Added tests/factories.py file and updated tests/test_model.py file](https://github.com/CSCI-GA-2820-SU23-001/orders/tree/create-order-api)
