### ISSUE TITLE
Need REST API to List Orders

### ISSUE THREAD

**Issue by yjhsieh2022** [CSCI-GA-2820-SU23-001/orders#3]
**As a** user
 **I need** a way to view all my orders
 **So that** I can keep track of my purchase history
   
 ### Details and Assumptions
•	The base URL would be /orders
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the server is available
 When I call the URL `GET/orders`
 Then it should return all the orders in the database
 ```

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/3?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022

**Comment by even1111112** [comment]
#24
