### ISSUE TITLE
Need REST API to Update an Order

### ISSUE THREAD

**Issue by yjhsieh2022** [CSCI-GA-2820-SU23-001/orders#4]
**As a** user
 **I need** a way to update my order
 **So that** I can make changes to it
   
 ### Details and Assumptions
•	The base URL would be /orders/{order_id}
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the server is available
 When I call the URL `PUT /orders/{order_id}
 Then it should update an order at the given URI with new information, providing the dull presentation
 ```

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/4?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
