### ISSUE TITLE
Need REST API to Delete an Order

### ISSUE THREAD

**Issue by yjhsieh2022** [CSCI-GA-2820-SU23-001/orders#5]
**As a** user
 **I need** a way to delete my order
 **So that** I can cancel my purchase if needed
   
 ### Details and Assumptions
•	The base URL would be /orders/{order_id}
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the server is available
 When I call the URI `DELETE /orders/{order_id}`
 Then it should remove the order identified by the given URI from the database
 ```

### Spec
`DELETE /orders/{order_id}`

Response:
`204_NO_CONTENT`

**Comment by PepperandSummer** [comment]
We need to consider about the foreign key connection when deleting one order data, otherwise, the database management may cause issue.

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/5?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
