### ISSUE TITLE
Setup GitHub bages

### ISSUE THREAD

**Issue by nicksome168** [CSCI-GA-2820-SU23-001/orders#55]
**As a** developer
**I need** a badge on the readme file
**So that**  I can understand the status of our build
   
 ### Details and Assumptions
 * Github workflow yml file will have to be created to configure github actions
 * We will need to add Github actions badge to Readme file
   
 ### Acceptance Criteria  
   
 ```gherkin
Given Github Actions have been properly implemented
When I look at the Readme file
Then it will indicate the status of our build
```

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/55?planning-poker) with Zenhub @even1111112 @nicksome168 @PepperandSummer @un-poco @yjhsieh2022

**Comment by yjhsieh2022** [comment]
Added codecov badge in README
