### ISSUE TITLE
Add Query String Support: find order by status to List Order API Endpoint

### ISSUE THREAD

**Issue by PepperandSummer** [CSCI-GA-2820-SU23-001/orders#57]
### Details:
1.routes.py

- Retrieve the value of the query parameter "status" from a network request. 
- If only status_query has a value (other queries are None or empty),  we executes: **orders = Order.find_by_status(status_query)**. This indicates that it wants to find orders that match the status only.

2. test_routes.py
- Verify that when a GET request is made to the specified base URL with a particular status query parameter, the server returns a response with HTTP 200 status code and the correct order status in the response data.

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/57?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
