### ISSUE TITLE
Add Query Capability: find order by status to the model

### ISSUE THREAD

**Issue by PepperandSummer** [CSCI-GA-2820-SU23-001/orders#59]
**Hints**
Here is the Find function in service/models.py. 
```
@classmethod
    def find(cls, by_id):
        """Finds a record by it's ID"""
        logger.info("Processing lookup for id %s ...", by_id)
        return cls.query.get(by_id)
```
Similarly, now we want to get the all the data filtered by a specific status. Since the results may not be only one, the used return function may be different.

**Details**
-Add a new function called find_by_status in service/models.py
-Add a test function in test/test_models.py and make sure it works

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/59?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
