### ISSUE TITLE
Need REST API to Read an Order

### ISSUE THREAD

**Issue by yjhsieh2022** [CSCI-GA-2820-SU23-001/orders#6]
**As a** user
 **I need** a way to view my order
 **So that** I can see the order details
   
 ### Details and Assumptions
•	The base URL would be /orders/{order_id}
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the server is available
 When I call URL `GET /orders/{order_id}`
 Then it should return the order identified by the given URI from the database
 ```

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/6?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
