### ISSUE TITLE
Add Query String Support: find order by customer_id to List Order API Endpoint

### ISSUE THREAD

**Issue by PepperandSummer** [CSCI-GA-2820-SU23-001/orders#60]
**As a** user
**I need** to make a query with a filter
**So that** I can pull specific records from the database

### Details and Assumptions
- The List method is already functioning on the Orders service
- The query provided will be a string
- The query string will be provided in the URL

### Acceptance Criteria
```text
Given a query made with a specific string
When the query is run
Then the results of the query identify all list items where any attribute contains the exact string
OR show the user that no results have been found
```

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/60?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
