### ISSUE TITLE
Add Query String Support: find order by customer_id and status to List Order API Endpoint

### ISSUE THREAD

**Issue by PepperandSummer** [CSCI-GA-2820-SU23-001/orders#62]
Details:
Add an if statement inside list_orders function in routes.py.
Add a test_list_orders_by_customer_id_and_status in test_routes.py

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/62?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022

**Comment by nicksome168** [comment]
@un-poco please add the story description
