### ISSUE TITLE
Create Kubernetes cluster on IBM Cloud

### ISSUE THREAD

**Issue by PepperandSummer** [CSCI-GA-2820-SU23-001/orders#64]
*As* an Order Manager
*I need* to create an environment to deploy our application to a Kubernetes cluster on IBM Cloud
*So that* I can gain better business agility and scale

#### Assumptions
• Allows for continuous delivery to be achieved
• Allows for creation of automated testing integrated with an automated CI/CD pipeline

#### Acceptance Criteria

1. All members create IBM Cloud accounts and are invited by the maintainer of our repo to their account
2. Kubernetes cluster is created, including a health check (/health endpoint)
3. dev namespace and prod namespace created
4. Service run as NodePort where Development port is: 31001 and the Production port is: 31002

**Comment by PepperandSummer** [comment]
**As a** developer
**I need** everyone makes an IBM Cloud account
**So that**  maintainer of repo can invite other members of our team to their IBM Cloud account and run Kubernetes Cluster successfully
   
 ### Details and Assumptions
 * Create a Kubernetes cluster on IBM Cloud
 * Add a /health endpoint to the service
   
 ### Acceptance Criteria  
   
 ```gherkin
Given setting up operations have been properly implemented
When check the status of Kubernetes
Then it will return {"status:" "OK"}, 200
```

**Comment by PepperandSummer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/64?planning-poker) with Zenhub @even1111112

**Comment by yjhsieh2022** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/64?planning-poker) with Zenhub @PepperandSummer @yjhsieh2022 @nicksome168 @even1111112 @un-poco

**Comment by nicksome168** [comment]
chenyingli200012@gmail.com
xd2218@nyu.edu
yw4930@nyu.edu
yh4519@nyu.edu
yc6371@nyu.edu
