### ISSUE TITLE
Need to create Order data model

### ISSUE THREAD

**Issue by nicksome168** [CSCI-GA-2820-SU23-001/orders#7]
**As a** developer
**I need** an order data model 
**So that** for all of the endpoints to use to store data
   
 ### Details and Assumptions
The order service is a collection of order items where each item represents a product id, its
quantity, and its price. You also will need to associate the order with a customer preferably through its customer id.

Please refer to the [ER diagram](https://dbdiagram.io/d/6494e1b302bd1c4a5eef0043)

 ### Acceptance Criteria  
   
 ```gherkin
 Given the database model is decided
 When we develop the inventory database
 Then we can reference the design document for tables, columns, relationships and datatypes
```

**Comment by nicksome168** [comment]
we can use dbdiagram.io to draw er diagram

**Comment by PepperandSummer** [comment]
When designing the data model, we need to consider **how many** entities we need and **relationship** among other entities, like **customer** and **inventory**. I think **inventory** means **items** in the project. This is some useful info related to order system in my previous project. I used two entities Order and Order Detail.  
This is not the correct and final data model for our project.

![Screen Shot 2023-06-17 at 1.15.26 AM.png](https://images.zenhubusercontent.com/64870c86de50ad9258e2aa0e/e1d6cf87-f1b8-4f02-8614-5ee7067f161a)![Screen Shot 2023-06-17 at 12.29.49 AM.png](https://images.zenhubusercontent.com/64870c86de50ad9258e2aa0e/ed0f5f65-e022-45c0-8036-e7ae33827b7a)

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/7?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022

**Comment by nicksome168** [comment]
https://dbdiagram.io/d/6494e1b302bd1c4a5eef0043
![Screenshot 2023-06-22 at 5.15.35 PM.png](https://images.zenhubusercontent.com/63bf8349be15815a5ed662a7/018ad0da-342c-44ac-a34f-98dcbfd9bbca)

**Comment by nicksome168** [comment]
Issues
1. we dont have the customer table, so when creating customer_id it gives "table not found" error
2. do we need to check each field's type
