### ISSUE TITLE
 Create Order in User Interface

### ISSUE THREAD

**Issue by un-poco** [CSCI-GA-2820-SU23-001/orders#89]
As an admin,
I need a UI that allows me to manipulate orders operations
So that I can create an order

## Details and Assumptions
* The form will intake customer_id, address(including Street, City, State, Postal Code), status, payment, total, and date.
* Order id is not needed to create the order, it is created internally to guarantee uniqueness.
* Date_created is added by the service to the data and is not a form input

## Acceptance Criteria
Given I input all the information into the UI,
When I click on the create button on the UI,
Then an order is created in the database,
And show a success or fail message on the UI.

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/89?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
