### ISSUE TITLE
Create bdd.yml File & Configure GitHub Actions to Implement Continuous Integration

### ISSUE THREAD

**Issue by un-poco** [CSCI-GA-2820-SU23-001/orders#91]
## Tasks:
* Create a bdd.yml file under the .github/workflows directory
* Configure bdd.yml in GitHub Actions to run test cases whenever there's a push to the master branch or a Pull Request is made
## Acceptance Criteria:
* GitHub Actions successfully runs test cases each time a push to the master branch or a Pull Request is made.

**Comment by un-poco** [comment]
Tasks:
Create a bdd.yml file under the .github/workflows directory
Configure bdd.yml in GitHub Actions to run test cases whenever there's a push to the master branch or a Pull Request is made
Acceptance Criteria: 
GitHub Actions successfully runs test cases each time a push to the master branch or a Pull Request is made.

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/91?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
