### ISSUE TITLE
Create scenarios (feature file and steps) for Create order

### ISSUE THREAD

**Issue by PepperandSummer** [CSCI-GA-2820-SU23-001/orders#95]
**As a** creator of this service
**I need** to create scenarios in the feature and steps files
**So that** I can perform BDD testing

#### Assumption
1. The UI already contains Create order functionality that can be tested

#### Acceptance Criteria
1. Given the scenarios for Create Order have been added
2. When I test Create Order functionality on UI
3. The test runs and passes

**Comment by nicksome168** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/orders-su23-001-6481b6f79c0ffe8ec198cba9/issues/CSCI-GA-2820-SU23-001/orders/95?planning-poker) with Zenhub @even1111112 @PepperandSummer @un-poco @yjhsieh2022
